import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  const [input, setInput] = useState('')
  return (
    <div className="container py-xxxl">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="d-flex justify-content-between">
        <div className="card bg-midnight p-xl w-33">
          <p className="small">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed
            voluptate, minima quo maiores quasi, repellendus, voluptas odio
            nulla perferendis harum officiis! Eligendi recusandae voluptas, vero
            sit eveniet aliquid dolores nihil.
          </p>
          <div className="input input__full-width">
            <label>Name</label>
            <input type="text" />
          </div>
          <button className="mt-xl btn  d-block">Click Here</button>
        </div>
        <div className="card bg-midnight p-xl w-33">
          <p className="small">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed
            voluptate, minima quo maiores quasi, repellendus, voluptas odio
            nulla perferendis harum officiis! Eligendi recusandae voluptas, vero
            sit eveniet aliquid dolores nihil.
          </p>
          <div className="input input__full-width">
            <label>Name</label>
            <input
              type="text"
              value={input}
              onChange={({ target }) => setInput(target.value)}
            />
          </div>
          <button
            onClick={async () => {
              const test = await fetch('/api/hello', {
                method: 'POST',
                body: input
              })
                .then(res => res.json())
                .then(data => data)
            }}
            className="mt-xl btn  d-block"
          >
            Click Here
          </button>
        </div>
      </div>
    </div>
  )
}
